apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    kafka: kafka-broker-1
  name: kafka-broker-1
spec:
  replicas: 1
  selector:
    matchLabels:
      kafka: kafka-broker-1
  template:
    metadata:
      labels:
        kafka: kafka-broker-1
    spec:
      containers:
      - env:
        - name: KAFKA_ADVERTISED_LISTENERS
          value: PLAINTEXT://kafka-broker-1:9092,LISTENER_LOCAL://localhost:19092
        - name: KAFKA_BROKER_ID
          value: "1"
        - name: KAFKA_COMPRESSION_TYPE
          value: producer
        - name: KAFKA_INTER_BROKER_LISTENER_NAME
          value: PLAINTEXT
        - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
          value: PLAINTEXT:PLAINTEXT,LISTENER_LOCAL:PLAINTEXT
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: zookeeper:2181
        image: confluentinc/cp-kafka:5.0.4
        imagePullPolicy: IfNotPresent
        name: kafka-broker-1
        ports:
        - containerPort: 19092
      hostname: kafka-broker-1
      restartPolicy: Always
status: {}
