apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    kafka: kafka-broker-2
  name: kafka-broker-2
spec:
  replicas: 1
  selector:
    matchLabels:
      kafka: kafka-broker-2
  template:
    metadata:
      labels:
        kafka: kafka-broker-2
    spec:
      containers:
      - env:
        - name: KAFKA_ADVERTISED_LISTENERS
          value: PLAINTEXT://kafka-broker-2:9092
        - name: KAFKA_BROKER_ID
          value: "2"
        - name: KAFKA_COMPRESSION_TYPE
          value: producer
        - name: KAFKA_INTER_BROKER_LISTENER_NAME
          value: PLAINTEXT
        - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
          value: PLAINTEXT:PLAINTEXT,LISTENER_LOCAL:PLAINTEXT
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: zookeeper:2181
        image: confluentinc/cp-kafka:5.0.4
        imagePullPolicy: "IfNotPresent"
        name: kafka-broker-2
        ports:
        - containerPort: 9092
        resources: {}
      hostname: kafka-broker-2
      restartPolicy: Always
status: {}
