apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\WINDOWS\system32\kompose.exe convert -f out.yml --indent 2 -o
      k8s
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: kafka-broker-2
  name: kafka-broker-2
spec:
  ports:
  - name: "29092"
    port: 29092
    targetPort: 29092
  selector:
    io.kompose.service: kafka-broker-2
status:
  loadBalancer: {}
