apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\WINDOWS\system32\kompose.exe convert -f out.yml --indent 2 -o
      k8s
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: twitter-to-kafka-service
  name: twitter-to-kafka-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: twitter-to-kafka-service
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\WINDOWS\system32\kompose.exe convert -f out.yml --indent 2
          -o k8s
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.network/application: "true"
        io.kompose.service: twitter-to-kafka-service
    spec:
      containers:
      - env:
        - name: JAVA_OPTS
          value: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
            -Xms128m -Xmx256m
        - name: KAFKA-CONFIG_BOOTSTRAP-SERVERS
          value: kafka-broker-1:9092, kafka-broker-2:9092, kafka-broker-3:9092
        - name: KAFKA-CONFIG_SCHEMA-REGISTRY-URL
          value: http://schema-registry:8081
        - name: KAFKA-CONFIG_TOPIC-NAME
          value: twitter-topic
        - name: LOGGING_LEVEL_COM_LAB_ALI
          value: info
        - name: LOGGING_LEVEL_ROOT
          value: info
        - name: SPRING_CLOUD_CONFIG_URI
          value: http://config-server:8888
        - name: TWITTER-TO-KAFKA-SERVICE_ENABLE-MOCK-TWEETS
          value: "true"
        image: vijayakrishnajava/com.lab.ali-twitter-to-kafka-service:0.0.1-SNAPSHOT
        imagePullPolicy: ""
        name: twitter-to-kafka-service
        ports:
        - containerPort: 5006
        resources: {}
        volumeMounts:
        - mountPath: /workspace/twitter-to-kafka-service/logs
          name: twitter-to-kafka-service-claim0
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: twitter-to-kafka-service-claim0
        persistentVolumeClaim:
          claimName: twitter-to-kafka-service-claim0
status: {}
