twitter-to-kafka-service:
  filterkeys:
    - vijay
    - krishna
    - seemakurthi
  welcome-message: Hello microservices!
  enable-mock-tweets: true
  mock-min-tweet-length: 5
  mock-max-tweet-length: 15
  mock-sleep-ms: 10000