apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\WINDOWS\system32\kompose.exe convert -f out.yml --indent 2 -o
      k8s
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: config-server
  name: config-server
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: config-server
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\WINDOWS\system32\kompose.exe convert -f out.yml --indent 2
          -o k8s
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.network/application: "true"
        io.kompose.service: config-server
    spec:
      containers:
      - env:
        - name: JAVA_OPTS
          value: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
            -Xms128m -Xmx256m
        - name: LOGGING_LEVEL_COM_LAB_ALI
          value: info
        - name: LOGGING_LEVEL_ROOT
          value: info
        - name: SPRING_CLOUD_CONFIG_SERVER_BOOTSTRAP
          value: "true"
        - name: SPRING_CLOUD_CONFIG_SERVER_GIT_DEFAULT-LABEL
          value: master
        - name: SPRING_CLOUD_CONFIG_SERVER_GIT_PASSWORD
          value: a3b0607babb1aeccd403b7f9171fe46999d606cd
        - name: SPRING_CLOUD_CONFIG_SERVER_GIT_URI
          value: https://github.com/vijayasjava/config-server-repository.git
        - name: SPRING_CLOUD_CONFIG_SERVER_GIT_USERNAME
          value: vijayasjava
        image: vijayakrishnajava/com.lab.ali-config-server:0.0.1-SNAPSHOT
        imagePullPolicy: ""
        name: config-server
        ports:
        - containerPort: 8888
        resources: {}
        volumeMounts:
        - mountPath: /workspace/config-server/logs
          name: config-server-claim0
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: config-server-claim0
        persistentVolumeClaim:
          claimName: config-server-claim0
status: {}
