apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\WINDOWS\system32\kompose.exe convert -f out.yml --indent 2 -o
      k8s
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: schema-registry
  name: schema-registry
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: schema-registry
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\WINDOWS\system32\kompose.exe convert -f out.yml --indent 2
          -o k8s
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.network/application: "true"
        io.kompose.service: schema-registry
    spec:
      containers:
      - env:
        - name: SCHEMA_REGISTRY_DEBUG
          value: "true"
        - name: SCHEMA_REGISTRY_HOST_NAME
          value: schema-registry
        - name: SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL
          value: zookeeper:2181
        - name: SCHEMA_REGISTRY_LISTENERS
          value: http://schema-registry:8081
        image: confluentinc/cp-schema-registry:5.0.4
        imagePullPolicy: ""
        name: schema-registry
        ports:
        - containerPort: 8081
        resources: {}
      hostname: schema-registry
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
