apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\WINDOWS\system32\kompose.exe convert -f out.yml --indent 2 -o
      k8s
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: twitter-to-kafka-service
  name: twitter-to-kafka-service
spec:
  ports:
  - name: "5006"
    port: 5006
    targetPort: 5006
  selector:
    io.kompose.service: twitter-to-kafka-service
status:
  loadBalancer: {}
